name: "${project.artifactId}"
main: "${project.groupId}.${project.artifactId}"
version: "${project.version}"
description: "${project.artifactId} Bukkit Plugin"
author: "BillyGalbreath"
api-version: "1.13"

commands:
  basiccommands:
    description: Reload the configs
    permission: command.basiccommands
    usage: /<command> (reload)
    aliases:
      - basiccmds
      - basiccmd
      - bcmds
      - bcmd
      - bc
  listbiomes:
    description: See visited biomes
    permission: command.listbiomes
    usage: /<command>
    aliases:
      - biomes
  listbreeds:
    description: See animals bred
    permission: command.listbreeds
    usage: /<command>
    aliases:
      - breeds
  listfoods:
    description: See foods eaten
    permission: command.listfoods
    usage: /<command>
    aliases:
      - foods
  listmobs:
    description: See mobs killed
    permission: command.listmobs
    usage: /<command>
    aliases:
      - mobs
  tpsbar:
    description: Toggle tps output above your hotbar
    permission: command.tpsbar
    usage: /<command>

permissions:
  command.basiccommands:
    description: Allows to reload the configs
    default: op
  command.listbiomes:
    description: Allows to list visited biomes
    default: op
  command.listbreeds:
    description: Allows to list animals bred
    default: op
  command.listfoods:
    description: Allows to list foods eaten
    default: op
  command.listmobs:
    description: Allows to list mobs killed
    default: op
  command.tpsbar:
    description: Allows to toggle tps bar
    default: op
